services:
  ms-search-food:
    build:
      context: ./ms-auth-user
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

# docker-compose build --no-cache
# docker-compose up
